FROM resin/rpi-raspbian:jessie

RUN apt update && apt install -y apt-transport-https curl

RUN curl https://bintray.com/user/downloadSubjectPublicKey?username=bintray | apt-key add -

RUN echo "deb https://dl.bintray.com/fg2it/deb-rpi-1b jessie main" | tee -a /etc/apt/sources.list.d/grafana.list

RUN sudo apt udpate && sudo apt install -y grafana

RUN sudo service grafana-server start

CMD ["sh"]